name: avs_image
description: "AVSImage package. A Flutter package that you can get and use images from local and network. Keep your images in the cache directory. You can also use your svg files with this package. Gradient color SVG is supported. All in one and easy to use."

version: 1.0.0
homepage: https://github.com/ahmetveysels
repository: https://github.com/ahmetveysels/avsimage
documentation: https://github.com/ahmetveysels/avsimage

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
