name: avs_image
description: "A Flutter package that you can get and use images and SVG from local and network . All in one and easy to use."
topics:
  - cache
  - image
  - network-image
version: 1.0.1
homepage: https://github.com/ahmetveysels
repository: https://github.com/ahmetveysels/avsimage

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter: null
